Bluetooth-Devices/bleak-retry-connector

- poetry.lock
- pyproject.toml
- src/bleak_retry_connector/__init__.py
- tests/test_init.py
dbus can hang on connect so we need an
overall safety timeout
> fix: add back the bleak overall safety timeout

- src/bleak_retry_connector/__init__.py
I did some more testing and 12s was the maximum it ever took without failure when the device was on the edge of range
> feat: improve chance of connecting with poor signal

- src/bleak_retry_connector/__init__.py
Sometimes we can't reconnect again because the callback didn't get a chance to run because control was never returned to the event loop.  We need to sleep 0 before reconnecting to ensure its run
> fix: race during disconnect error

- .flake8
- src/bleak_retry_connector/__init__.py
- tests/test_init.py
- We will try to freshen the device from
the global BlueZ manager. If anything goes
wrong we will use the potentially stale BLEDevice
since we are not using a public api (there
is no public api for this)
> feat: handle stale BLEDevices when an adapter goes offline

- src/bleak_retry_connector/__init__.py
- tests/test_init.py
Bleak 0.17 supports connecting to devices that are already connected in BlueZ.
We now detect this and adjust the BLEDevice to point to the already
connected device so they do not have to wait for a connection.
This also fixes a race where the connection times out but the connection is actually
made on the bus but we think it failed because we hit the timeout, so the next attempt
will instead sail right though and be connected.
> feat: do not disconnect unexpectedly connected devices if bleak supports reusing them

- src/bleak_retry_connector/__init__.py
Bleak now wants the disconnected_callback in the constructor
need to update aiohomekit as well
`Sep 26 05:03:12 homeassistant homeassistant[485]: TypeError: AIOHomeKitBleakClient.__init__() got an unexpected keyword argument 'disconnected_callback'`
> fix: set disconnected_callback in the constructor for newer bleak compat

- poetry.lock
- pyproject.toml
- src/bleak_retry_connector/__init__.py
- tests/test_init.py
Bleak is moving `.rssi` to the adv instead of device. We need to prepare for this.
Need to fix this failure on macos
```
self = <bleak.backends.corebluetooth.client.BleakClientCoreBluetooth object at 0x1125923e0>, address_or_ble_device = BLEDevice(FA:23:9D:AA:45:46, name)
kwargs = {'disconnected_callback': <MagicMock id='4602793936'>, 'timeout': 10.0, 'winrt': {}}
def __init__(self, address_or_ble_device: Union[BLEDevice, str], **kwargs):
super(BleakClientCoreBluetooth, self).__init__(address_or_ble_device, **kwargs)
self._peripheral: Optional[CBPeripheral] = None
self._delegate: Optional[PeripheralDelegate] = None
self._central_manager_delegate: Optional[CentralManagerDelegate] = None
if isinstance(address_or_ble_device, BLEDevice):
>           (
self._peripheral, …
```
> feat: update for new bleak 19

- src/bleak_retry_connector/__init__.py
When we were debugging the esphome timeouts, logging the full trace was useful, but now it is is too noisy as timeouts are expected and we have moved on to fixing other issues
> fix: reduce logging as timeouts are expected

- src/bleak_retry_connector/__init__.py
The timeout was not long enough to connect to some of the slower older devices
> fix: adjust connect timeout to match macos write timeout

- src/bleak_retry_connector/__init__.py
Should reduce the change we hit https://github.com/espressif/esp-idf/issues/5105
> fix: teach the connector about more esp32 errors and times

- src/bleak_retry_connector/__init__.py
- tests/test_init.py
Each call to get_device would try over and over to connect to dbus when the socket is missing. This is normal when dbus is not setup and only using bluetooth proxies
fixes #69
> fix: stop trying to check dbus once the socket is missing

- src/bleak_retry_connector/__init__.py
We have been using this with almost every integration for a long time, and its
proven itself. Flip the default to True as the esp32s are unreliable without it
anyways
> fix: enable service cache by default since esp32s are unreliable without it

- src/bleak_retry_connector/__init__.py
- tests/test_init.py
Since we can get a new BLEDevice after we call connect, we should not log the adapter as it may be stale.
The logging should happen in HA instead.
> fix: avoid logging connecting and connected since our BLEDevice may be stale

- src/bleak_retry_connector/__init__.py
- tests/test_init.py
Sometimes the ESP32 or the BlueZ stack will resolve services incorrectly so we need a way to clear the cache
> feat: add function to clear the cache

- src/bleak_retry_connector/bluez.py
Since a callback is required, we make it as generic as possible to avoid future breaking changes
> fix: _on_characteristic_value_changed in BleakSlotManager should accept any arguments

- src/bleak_retry_connector/__init__.py
- tests/conftest.py
- tests/test_init.py
related https://github.com/home-assistant/core/pull/84512
> feat: remove freshen fallback logic since Home Assistant always provides us the best path to the device now

- src/bleak_retry_connector/__init__.py
This avoids an exception on Windows because socket.CMSG_LEN is only available on UNIX platforms.
```
File "bleak_retry_connector/__init__.py", line 18, in <module>
from bluetooth_adapters import load_history_from_managed_objects
File "bluetooth_adapters/__init__.py", line 12, in <module>
from .dbus import (
File "bluetooth_adapters/dbus.py", line 10, in <module>
from dbus_fast import BusType, Message, MessageType, unpack_variants
File "dbus_fast/__init__.py", line 1, in <module>
from . import aio, glib, introspection, message_bus, proxy_object, service
File "dbus_fast/aio/__init__.py", line 1, in <module>
from .message_bus import MessageBus
File "dbus_fast/aio\message_bus.py", line 29, in <module>
from .message_reader import build_message_reader
File "dbus_fast/aio/message_reader.py", …
```
> fix: only import from bluetooth_adapters when running on linux

- .github/workflows/ci.yml
- .github/workflows/labels.yml
- .pre-commit-config.yaml
- .readthedocs.yml
- docs/source/conf.py
- pyproject.toml
Following the schema of supporting the current and one previous Python release this drops support for Python 3.9.
BREAKING CHANGE: In preparation for the use of Python 3.10 typing features such as ParamSpec, which is unavailable on Python 3.9.
> chore!: drop Python 3.9 support

- src/bleak_retry_connector/__init__.py
- tests/test_init.py
This should be the correct way of dealing with both of these types and mypy.
> fix: typing for generic BleakClient classes and the retry_bluetooth_connection_error decorator

- pyproject.toml
- src/bleak_retry_connector/__init__.py
- src/bleak_retry_connector/bluez.py
- src/bleak_retry_connector/dbus.py
- src/bleak_retry_connector/util.py
async_timeout < 4.0.3 did not work correctly with py3.11, we now use asyncio.timeout on py3.11
> fix: ensure timeouts work with py3.11

- src/bleak_retry_connector/__init__.py
- tests/test_init.py
fixes #107
```
2023-10-25 17:10:38.888 ERROR (MainThread) [homeassistant.components.improv_ble.config_flow] Unexpected exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/improv_ble/config_flow.py", line 399, in _try_call
return await func
^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/improv_ble_client/client.py", line 184, in can_identify
return await self._execute(_can_identify)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 471, in _async_wrap_bluetooth_connection_error_retry
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/improv_ble_client/client.py", line 291, in _execute
await …
```
> feat: handle services changed during connecting

- src/bleak_retry_connector/bluez.py
- tests/test_bluez.py
This PR fixes a KeyError exception that occurs when a Bluetooth adapter is unplugged while a device connection is in progress. The issue happens because the disconnect callback tries to release a slot for an adapter that has already been removed from the internal tracking structures.
```
2025-08-21 13:49:44.356 ERROR (MainThread) [dbus_fast.message_bus] A message handler raised an exception: 'hci1'
Traceback (most recent call last):
File "src/dbus_fast/message_bus.py", line 797, in dbus_fast.message_bus.BaseMessageBus._process_message
File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/manager.py", line 1077, in _parse_msg
watcher.on_connected_changed(new_connected)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
File …
```
> fix: prevent KeyError when adapter unplugged during connection
